language: generic

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y curl libarchive-tools git; fi
  - cd tests

script:
  - ./test.sh
