version: {build}
image:
- Ubuntu
- macOS
build_script:
- sh: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y curl libarchive-tools git; fi; && cd tests
test_script:
- sh: ./test.sh