version: 1.0.{build}
image:
- Ubuntu
- macOS
build_script:
- sh: cd tests && if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu" ]]; then sudo apt-get update && sudo apt-get install -y curl libarchive-tools git; fi;
test_script:
- sh: ./test.sh